/*
	SUM - Computes the sum of the non-null input values
*/
SELECT SUM(TOTAL)
FROM ORDERS;


SELECT date, TOTAL
FROM ORDERS
order by 1 asc


SELECT C.FIRST_NAME,
	SUM(O.TOTAL) AS TOTAL
FROM ORDERS O
INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.ID
GROUP BY C.FIRST_NAME
ORDER BY TOTAL ASC